[env]
TERM = "xterm-256color"

[general]
import=[
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[font]
size = 12
normal = { family = "IntoneMono Nerd Font", style = "Regular" }
bold = { family = "IntoneMono Nerd Font", style = "Bold" }
italic = { family = "IntoneMono Nerd Font", style = "Italic" }
